# Canal 配置文件参数示例

canal:
  # canal deployer 使用的数据库用户名
  username: canal
  # canal deployer 使用的数据库密码
  password: canal

  # canal 监听的表, 未配置时以 canal deployer 为准
  # 监听全表             .*\..*
  # 监听指定 schema      test\..*
  # 监听指定表            test.table1
  # 综合监听(逗号分隔)     test1\..*,test2.table1,test2.table2
  subscribe: ds0\..*

  # 扩展功能
  extension:
    # 从表相关
    slave:
      # 从表所属 schema
      schema: backup
      # 从表表名前缀
#      table-name-prefix: backup_