server:
  port: 8080
  servlet:
    context-path: /demo-canal
    encoding:
      force: true   # true = 使用当前配置文件进行编码, 可配合 charset: utf-8 使用

# Canal 数据监听配置
canal:
  username: canal                 # canal deployer 用户名
  password: canpiH-garzy2-nacbyk  # canal deployer 密码

  # canal 监听的表, 未配置时以 canal deployer 为准
  # 监听全表             .*\..*
  # 监听指定 schema      test\..*
  # 监听指定表            test.table1
  # 综合监听(逗号分隔)     test1\..*,test2.table1,test2.table2
  subscribe: data\..*

  # canal 扩展功能
  extension:
    # 从表相关
    slave:
      # 从表所属 schema
      schema: backup
      # 从表表名前缀
#      table-name-prefix: backup_

# Spring 配置
spring:
  application:
    name: demo-canal
  main:
    allow-bean-definition-overriding: true # true = 允许后覆盖相同名称的 bean, 防止项目集成后出现重复定义的冲突

  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: "RVsdbgjs~4921"
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
    druid:
      test-while-idle: true
      validation-query: SELECT 1

  # JPA
  jpa:
    show-sql: true        # log 中打印 sql 语句, 便于排查错误
    open-in-view: false   # true = 保持数据库连接直至 controller 执行完

  # 文件大小限制
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  # Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # Thymeleaf
  thymeleaf:
    check-template-location: false

# 日志
logging:
  level:
    ROOT: info  # 最低展示级别 (error > warn > info > debug)
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %green(%logger{50}).%M-%L - %msg %n'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %green(%logger{50}).%M-%L - %msg %n'
  logback:
    rolling policy:
      max-history: 10 # 最大保留时长(天)
      max-file-size: 100MB
  file:
    path: "demo-canal/logs"