server:
  # 端口
  port: 8080
  servlet:
    # 访问路径前缀
    context-path: /demo
    encoding:
      # 使用当前配置文件进行编码, 可配合 charset: utf-8 使用
      force: true

spring:
  application:
    name: demo
  main:
    # 允许后覆盖相同名称的 bean, 防止项目集成后出现重复定义的冲突
    allow-bean-definition-overriding: true

  # 数据库
  datasource:
    # 驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 链接
    url: jdbc:mysql://localhost:3306/data?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    # 用户信息
    username: root
    password: "12345678"
    # 类型
    type: com.zaxxer.hikari.HikariDataSource
    # 连接池
    hikari:
      minimum-idle: 3
      maximum-pool-size: 3
      idle-timeout: 120000

  # JPA
  jpa:
    # log 中打印 sql 语句, 便于排查错误
    show-sql: true

  # Elasticsearch
  elasticsearch:
    uris: localhost:9200
    username: root
    password: root
    connection-timeout: 1000
    socket-timeout: 60000

  mvc:
    pathmatch:
      # 用于解决因 Swagger 与 Spring 版本问题导致的报错
      matching-strategy: ant_path_matcher

# 日志
logging:
  level:
    # 最低展示级别, 减少非必要信息的输出 (error > warn > info > debug)
    ROOT: info
  file:
    path: "logs"
  # 输出格式
  pattern:
    # 参数含义: {时间} [线程名] 日志级别 日志所属类. 方法名-行号 - 错误信息及换行
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %yellow(%logger{50}).%M-%L - %msg %n'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %yellow(%logger{50}).%M-%L - %msg %n'
  logback:
    rollingpolicy:
      # 最大保留时长(天)
      max-history: 10
      max-file-size: 100MB

# Swagger
springdoc:
  swagger-ui:
    # 测试环境启用, 生产环境需关闭
    enabled: false
