server:
  # 端口
  port: 8080
  servlet:
    # 访问路径前缀
    context-path: /demo
    encoding:
      # 使用当前配置文件进行编码, 可配合 charset: utf-8 使用
      force: true


# Canal 参数
canal:
  # canal deployer 使用的数据库用户名
  username: canal
  # canal deployer 使用的数据库密码
  password: RVsdbgjs~4921

  # canal 监听的表, 未配置时以 canal deployer 为准
  # 监听全表             .*\..*
  # 监听指定 schema      test\..*
  # 监听指定表            test.table1
  # 综合监听(逗号分隔)     test1\..*,test2.table1,test2.table2
  subscribe: demo\..*

  # 扩展功能
  extension:
    # 从表相关
    slave:
      # 从表所属 schema
      schema: backup
      # 从表表名前缀
#      table-name-prefix: backup_

# MinIO 文件管理 part 1
minio:
  endpoint: http://localhost:9000                       # 服务器地址
  accessKey: lGVSfahkzSI8W0GmH3ur                       # 访问密钥, 在服务器网页管理界面配置
  secretKey: 7L6KUYuOSKToU7DlCIicGO1tUfH62xvM8wHzhlAO   # 访问密钥的密码, 在服务器网页管理界面配置
  bucketName: test_bucket                               # 默认 bucket 名称
  fileUrlHost: http://172.16.30.35:9000/customized-minio/   # 手动指定的 MinIO 文件访问前缀, 用于 nginx 配置后

# Spring Auto-Configuration
spring:
  application:
    name: demo
  main:
    # 允许后覆盖相同名称的 bean, 防止项目集成后出现重复定义的冲突
    allow-bean-definition-overriding: true

  data:
    web:
      pageable:
        # 分页查询页码从 1 而不是 0 开始
        one-indexed-parameters: true

  #   Sharding 数据库
  #  datasource:
  #    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
  #    url: jdbc:shardingsphere:classpath:sharding-dev.yaml
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    # 用户信息
    username: root
    password: "RVsdbgjs~4921"
    # 连接池
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
  task:
    # 线程池
    execution:
      pool:
        max-size: 16
        core-size: 16
        keep-alive: 10s
        queue-capacity: 100
        allow-core-thread-timeout: true
      # 线程名称前缀
      thread-name-prefix: async-task-

    # 定时任务
    scheduling:
      pool:
        size: 10

  # Elasticsearch
  elasticsearch:
    uris: http://localhost:9200
    socket-timeout: 60000
    connection-timeout: 60000
    password:

  # JPA
  jpa:
    # log 中打印 sql 语句, 便于排查错误
    show-sql: true
    # true = 保持数据库连接直至 controller 执行完
    open-in-view: false

  # Kafka
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: demo-topic
    consumer:
      group-id: demo-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 没有 offset 时配置 offset 的规则
      auto-offset-reset: earliest
      # 是否允许自动提交
      enable-auto-commit: false
      # 拉取数据时, 每批次最大数据量
      max-poll-records: 1000
      fetch-max-wait: 3s
      properties:
        isolation.level: read_committed
    listener:
      type: batch
      # 提交模式
      ack-mode: manual_immediate
      idle-event-interval: 10s
      concurrency: 4
      missing-topics-fatal: false
    producer:
      # 消息处理成功的条件: 0 不返回, 1 leader 收到返回成功, all/-1 全员收到返回成功
      acks: 1

  # MinIO 文件管理 part 2
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  # Neo4j
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: RVsdbgjs~4921

  # Redis
  redis:
    host: localhost
    port: 6379
    # 需要时间单位
    timeout: 10s
    lettuce:
      pool:
        max-active: 8
        # 需要时间单位
        max-wait: -1s
        max-idle: 8
        min-idle: 0

  # Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # Thymeleaf
  thymeleaf:
    check-template-location: false
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName=SsmScheduler:

# 日志
logging:
  level:
    # 最低展示级别, 减少非必要信息的输出 (error > warn > info > debug)
    ROOT: info
  # 输出格式
  pattern:
    # 参数: {时间} [线程名] 日志级别 日志所属类. 方法名-行号 - 错误信息及换行
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %green(%logger{50}).%M-%L - %msg %n'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %green(%logger{50}).%M-%L - %msg %n'
  logback:
    rolling policy:
      # 最大保留时长(天)
      max-history: 10
      max-file-size: 100MB
  file:
    path: "logs"